### ISSUE TITLE
大哥可以给个微信啥的吗

### ISSUE THREAD

**Issue by tuojianSun** [pureqh/Troy#1]
我是刚入门的小白，觉得你的项目和博客都挺不错，但是你的博客有些文章需要密码= =所以大哥能给你微信啥的吗

**Comment by pureqh** [comment]
是哪些文章呢 可以给我发一下链接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pureqh/Troy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 下午5:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pureqh/Troy] 大哥可以给个微信啥的吗 (Issue #1)





 
我是刚入门的小白，觉得你的项目和博客都挺不错，但是你的博客有些文章需要密码= =所以大哥能给你微信啥的吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
